[package]
name = "stackdog"
version = "0.1.0"
authors = ["Vasili Pascal <info@try.direct>"]
edition = "2018"

#[package.metadata.docs.rs]
#features = ["openssl", "rustls", "compress", "secure-cookies"]
#
#[dependencies]
#actix-web = { version = "3.0.0-alpha.2", features=["rustls"] }
#actix-rt = "1.1.1"
#actix-service = "1.0.6"
#actix-cors = "0.3.0"
#actix-http = "2.1.0"
#actix = "0.10"
#log = "0.4.11"
#env_logger = "0.7.1"
#serde = "1.0.116"
#serde_derive = "1.0.116"
#serde_json = "1.0.57"
#dotenv = "0.15.0"
#futures = "0.3.5"
#failure = "0.1.8"
#derive_more = "0.99.10"
#jsonwebtoken = "7.2.0"
#bcrypt = "0.8.2"
#actix-tls = "2.0.0"
#awc = { version = "2.0.0", default-features = false }
#open-ssl = { package = "openssl", version = "0.10", optional = true }
#rust-tls = { package = "rustls", version = "0.18.0", optional = true }
#
#[features]
## openssl
#openssl = ["actix-tls/openssl", "awc/openssl", "open-ssl"]
## rustls
#rustls = ["actix-tls/rustls", "awc/rustls", "rust-tls"]
#default = ["compress"]
#
## content-encoding support
#compress = ["actix-http/compress", "awc/compress"]
#
## sessions feature
#secure-cookies = ["actix-http/secure-cookies"]
#
#[dependencies.chrono]
#version = "0.4.15"
#features = ["serde"]