version: '3'
services:
  stackdog:
    container_name: backend
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    restart: always
    ports:
    - "5000:5000"
    env_file: .env