name: Githubflow

on:
  push:
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notifications to Telegram
        run: curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} -d text="${MESSAGE}" >> /dev/null
        env:
          MESSAGE: "Issue ${{ github.event.action }}: \n${{ github.event.issue.html_url }}"
